// This file contains placeholder data that you'll be replacing with real data in the Data Fetching chapter:
// https://nextjs.org/learn/dashboard-app/fetching-data
import { User, UserRole, Project, ProjectType, ProjectStatus, ProjectPriority, Requirement, RequirementStatus, RequirementPriority, RequirementType, Task, Defect } from './definitions';

const users: (User & { role: UserRole })[] = [
  {
    id: "410544b2-4001-4271-9855-fec4b6a6442a",
    nickname: "admin",
    password: "123456",
    role: "user",
    totalPoints: 0,
  },
  {
    id: "550e8400-e29b-41d4-a716-446655440000",
    nickname: "testuser",
    password: "password123",
    role: "user",
    totalPoints: 0,
  },
  {
    id: "6ba7b810-9dad-11d1-80b4-00c04fd430c8",
    nickname: "敏捷小助手",
    password: "agile2024",
    role: "user",
    totalPoints: 0,
  },
  {
    id: "6ba7b811-9dad-11d1-80b4-00c04fd430c8",
    nickname: "developer",
    password: "dev123",
    role: "user",
    totalPoints: 0,
  },
  {
    id: "superadmin-001",
    nickname: "wuyucun",
    password: "wyc7758775",
    role: "superadmin",
    totalPoints: 0,
  },
];

const customers = [
  {
    id: "d6e15727-9fe1-4961-8c5b-ea44a9bd81aa",
    name: "Evil Rabbit",
    email: "evil@rabbit.com",
    image_url: "/customers/evil-rabbit.png",
  },
  {
    id: "3958dc9e-712f-4377-85e9-fec4b6a6442a",
    name: "Delba de Oliveira",
    email: "delba@oliveira.com",
    image_url: "/customers/delba-de-oliveira.png",
  },
  {
    id: "3958dc9e-742f-4377-85e9-fec4b6a6442a",
    name: "Lee Robinson",
    email: "lee@robinson.com",
    image_url: "/customers/lee-robinson.png",
  },
  {
    id: "76d65c26-f784-44a2-ac19-586678f7c2f2",
    name: "Michael Novotny",
    email: "michael@novotny.com",
    image_url: "/customers/michael-novotny.png",
  },
  {
    id: "CC27C14A-0ACF-4F4A-A6C9-D45682C144B9",
    name: "Amy Burns",
    email: "amy@burns.com",
    image_url: "/customers/amy-burns.png",
  },
  {
    id: "13D07535-C59E-4157-A011-F8D2EF4E0CBB",
    name: "Balazs Orban",
    email: "balazs@orban.com",
    image_url: "/customers/balazs-orban.png",
  },
];

const invoices = [
  {
    customer_id: customers[0].id,
    amount: 15795,
    status: "pending",
    date: "2022-12-06",
  },
  {
    customer_id: customers[1].id,
    amount: 20348,
    status: "pending",
    date: "2022-11-14",
  },
  {
    customer_id: customers[4].id,
    amount: 3040,
    status: "paid",
    date: "2022-10-29",
  },
  {
    customer_id: customers[3].id,
    amount: 44800,
    status: "paid",
    date: "2023-09-10",
  },
  {
    customer_id: customers[5].id,
    amount: 34577,
    status: "pending",
    date: "2023-08-05",
  },
  {
    customer_id: customers[2].id,
    amount: 54246,
    status: "pending",
    date: "2023-07-16",
  },
  {
    customer_id: customers[0].id,
    amount: 666,
    status: "pending",
    date: "2023-06-27",
  },
  {
    customer_id: customers[3].id,
    amount: 32545,
    status: "paid",
    date: "2023-06-09",
  },
  {
    customer_id: customers[4].id,
    amount: 1250,
    status: "paid",
    date: "2023-06-17",
  },
  {
    customer_id: customers[5].id,
    amount: 8546,
    status: "paid",
    date: "2023-06-07",
  },
  {
    customer_id: customers[1].id,
    amount: 500,
    status: "paid",
    date: "2023-08-19",
  },
  {
    customer_id: customers[5].id,
    amount: 8945,
    status: "paid",
    date: "2023-06-03",
  },
  {
    customer_id: customers[2].id,
    amount: 1000,
    status: "paid",
    date: "2022-06-05",
  },
];

const revenue = [
  { month: "Jan", revenue: 2000 },
  { month: "Feb", revenue: 1800 },
  { month: "Mar", revenue: 2200 },
  { month: "Apr", revenue: 2500 },
  { month: "May", revenue: 2300 },
  { month: "Jun", revenue: 3200 },
  { month: "Jul", revenue: 3500 },
  { month: "Aug", revenue: 3700 },
  { month: "Sep", revenue: 2500 },
  { month: "Oct", revenue: 2800 },
  { month: "Nov", revenue: 3000 },
  { month: "Dec", revenue: 4800 },
];

const projects: Project[] = [
  {
    id: 'proj-1',
    name: '敏捷人员管理系统',
    description: '基于Next.js的现代化人员管理平台',
    type: 'code',
    status: 'normal',
    priority: 'high',
    goals: ['实现用户管理', '实现项目管理', '实现任务管理'],
    tags: ['Next.js', 'TypeScript', 'React'],
    startDate: '2024-01-15',
    endDate: '2024-03-30',
    progress: 75,
    points: 0,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-20T00:00:00.000Z'
  },
  {
    id: 'proj-2',
    name: '健身计划',
    description: '通过规律运动增强体质，保持健康生活方式',
    type: 'life',
    status: 'normal',
    priority: 'medium',
    goals: ['减肥5公斤', '增肌', '每周运动3次'],
    tags: ['健康', '运动', '健身'],
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    progress: 45,
    points: 0,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-19T00:00:00.000Z'
  },
  {
    id: 'proj-3',
    name: '学习英语',
    description: '提升英语水平，为工作学习做准备',
    type: 'life',
    status: 'at_risk',
    priority: 'medium',
    goals: ['考过六级', '阅读英文原版书籍', '能流利对话'],
    tags: ['英语', '学习', '语言'],
    startDate: '2024-02-01',
    endDate: '2024-06-30',
    progress: 0,
    points: 0,
    createdAt: '2024-01-18T00:00:00.000Z',
    updatedAt: '2024-01-18T00:00:00.000Z'
  },
  {
    id: 'proj-4',
    name: '个人博客',
    description: '搭建个人博客网站，记录学习心得',
    type: 'code',
    status: 'at_risk',
    priority: 'low',
    goals: ['完成基础功能', '添加评论系统', '部署上线'],
    tags: ['博客', '前端', 'React'],
    startDate: '2024-01-10',
    endDate: '2024-06-01',
    progress: 30,
    points: 0,
    createdAt: '2024-01-10T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z'
  },
  {
    id: 'proj-5',
    name: '读书计划',
    description: '通过阅读扩展知识面，提升思维能力',
    type: 'life',
    status: 'normal',
    priority: 'high',
    goals: ['读完12本书', '写读书笔记', '分享读后感'],
    tags: ['阅读', '知识', '成长'],
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    progress: 15,
    points: 0,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-19T00:00:00.000Z'
  },
  {
    id: 'proj-6',
    name: '开源贡献',
    description: '参与开源项目，提升技术能力与社区影响力',
    type: 'code',
    status: 'out_of_control',
    priority: 'high',
    goals: ['每月提交PR', '参与代码审查', '撰写技术文档'],
    tags: ['开源', 'GitHub', '协作'],
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    progress: 10,
    points: 0,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-18T00:00:00.000Z'
  },
  {
    id: 'proj-7',
    name: '冥想习惯',
    description: '培养每日冥想习惯，提升专注力与情绪管理',
    type: 'life',
    status: 'normal',
    priority: 'low',
    goals: ['每日冥想10分钟', '尝试不同冥想方式', '记录冥想感受'],
    tags: ['冥想', '心理健康', '习惯'],
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    progress: 60,
    points: 0,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-20T00:00:00.000Z'
  },
  {
    id: 'proj-8',
    name: '周报自动化',
    description: '用脚本自动汇总本周工作内容并生成周报，节省重复劳动时间',
    type: 'code',
    status: 'normal',
    priority: 'medium',
    goals: ['对接日历与任务', '生成 Markdown 周报', '支持一键复制'],
    tags: ['自动化', '效率', '脚本'],
    startDate: '2024-02-01',
    endDate: '2025-03-01',
    progress: 20,
    points: 0,
    createdAt: '2024-02-01T00:00:00.000Z',
    updatedAt: '2024-02-01T00:00:00.000Z'
  },
  {
    id: 'proj-9',
    name: '家庭记账',
    description: '记录每日收支，按分类统计并生成简单图表，便于家庭财务规划',
    type: 'life',
    status: 'at_risk',
    priority: 'high',
    goals: ['分类记账', '月度报表', '预算提醒'],
    tags: ['理财', '记账', '家庭'],
    startDate: '2024-01-15',
    endDate: '2025-06-30',
    progress: 40,
    points: 0,
    createdAt: '2024-01-15T00:00:00.000Z',
    updatedAt: '2024-01-15T00:00:00.000Z'
  },
  {
    id: 'proj-10',
    name: '知识库搭建',
    description: '用 Notion 或自建 Wiki 整理技术笔记与项目文档，形成可检索的知识库',
    type: 'code',
    status: 'normal',
    priority: 'medium',
    goals: ['选定工具', '迁移旧笔记', '建立索引'],
    tags: ['知识管理', '文档', 'Wiki'],
    startDate: '2024-03-01',
    endDate: '2025-12-31',
    progress: 10,
    points: 0,
    createdAt: '2024-03-01T00:00:00.000Z',
    updatedAt: '2024-03-01T00:00:00.000Z'
  },
  {
    id: 'proj-11',
    name: '早睡早起计划',
    description: '调整作息，目标 23 点前入睡、7 点前起床，并记录睡眠质量与白天精力',
    type: 'life',
    status: 'normal',
    priority: 'high',
    goals: ['固定作息', '记录睡眠', '评估精力'],
    tags: ['健康', '作息', '习惯'],
    startDate: '2024-02-10',
    endDate: '2025-02-10',
    progress: 25,
    points: 0,
    createdAt: '2024-02-10T00:00:00.000Z',
    updatedAt: '2024-02-10T00:00:00.000Z'
  },
  {
    id: 'proj-12',
    name: 'Side Project 上线',
    description: '完成一个最小可行产品并部署上线，包含基础功能与简单监控与回滚方案',
    type: 'code',
    status: 'at_risk',
    priority: 'high',
    goals: ['MVP 功能', '部署流程', '监控与告警'],
    tags: ['Side Project', '部署', '运维'],
    startDate: '2024-01-20',
    endDate: '2025-05-01',
    progress: 35,
    points: 0,
    createdAt: '2024-01-20T00:00:00.000Z',
    updatedAt: '2024-01-20T00:00:00.000Z'
  }
];

const requirements: Requirement[] = [
  {
    id: 'REQ-001',
    projectId: 'proj-1',
    title: '用户登录功能优化',
    description: '改进用户登录体验，支持多种登录方式，增加记住密码功能',
    type: 'enhancement',
    status: 'development',
    priority: 'high',
    assignee: '张三',
    reporter: '产品经理',
    createdDate: '2024-01-15',
    dueDate: '2024-02-15',
    storyPoints: 8,
    points: 0,
    tags: ['用户体验', '登录', '安全']
  },
  {
    id: 'REQ-002',
    projectId: 'proj-1',
    title: '数据导出功能',
    description: '支持将用户数据导出为Excel和PDF格式，包含筛选和排序功能',
    type: 'feature',
    status: 'review',
    priority: 'medium',
    assignee: '李四',
    reporter: '客户',
    createdDate: '2024-01-20',
    dueDate: '2024-03-01',
    storyPoints: 13,
    points: 0,
    tags: ['数据', '导出', 'Excel', 'PDF']
  },
  {
    id: 'REQ-003',
    projectId: 'proj-1',
    title: '移动端响应式适配',
    description: '优化移动端显示效果，确保在各种屏幕尺寸下的良好体验',
    type: 'enhancement',
    status: 'approved',
    priority: 'high',
    assignee: '王五',
    reporter: 'UI设计师',
    createdDate: '2024-01-25',
    dueDate: '2024-02-28',
    storyPoints: 21,
    points: 0,
    tags: ['移动端', '响应式', 'UI']
  },
  {
    id: 'REQ-004',
    projectId: 'proj-1',
    title: '性能监控系统',
    description: '建立系统性能监控机制，实时监控系统运行状态和性能指标',
    type: 'feature',
    status: 'draft',
    priority: 'medium',
    assignee: '赵六',
    reporter: '运维团队',
    createdDate: '2024-02-01',
    dueDate: '2024-04-01',
    storyPoints: 34,
    points: 0,
    tags: ['监控', '性能', '运维']
  },
  {
    id: 'REQ-005',
    projectId: 'proj-1',
    title: '修复文件上传bug',
    description: '解决大文件上传时出现的超时和进度显示错误问题',
    type: 'bugfix',
    status: 'testing',
    priority: 'critical',
    assignee: '钱七',
    reporter: '测试团队',
    createdDate: '2024-02-05',
    dueDate: '2024-02-10',
    storyPoints: 5,
    points: 0,
    tags: ['bug修复', '文件上传', '超时']
  },
  {
    id: 'REQ-006',
    projectId: 'proj-1',
    title: '用户权限管理重构',
    description: '重新设计用户权限管理系统，支持更细粒度的权限控制',
    type: 'feature',
    status: 'completed',
    priority: 'high',
    assignee: '孙八',
    reporter: '安全团队',
    createdDate: '2023-12-01',
    dueDate: '2024-01-31',
    storyPoints: 55,
    points: 0,
    tags: ['权限', '安全', '重构']
  }
];

const tasks: Task[] = [
  {
    id: 'task-1',
    projectId: 'proj-1',
    title: 'User Login Feature',
    description: 'Implement user login, registration and password reset',
    status: 'in_progress',
    priority: 'high',
    assignee: 'Zhang San',
    dueDate: '2024-01-15',
    estimatedHours: 16,
    completedHours: 8,
    tags: ['Frontend', 'Auth'],
  },
  {
    id: 'task-2',
    projectId: 'proj-1',
    title: 'API Documentation',
    description: 'Write complete API documentation with examples',
    status: 'todo',
    priority: 'medium',
    assignee: 'Li Si',
    dueDate: '2024-01-20',
    estimatedHours: 12,
    completedHours: 0,
    tags: ['Documentation', 'Backend'],
  },
  {
    id: 'task-3',
    projectId: 'proj-1',
    title: 'Database Optimization',
    description: 'Optimize query performance and add indexes',
    status: 'review',
    priority: 'high',
    assignee: 'Wang Wu',
    dueDate: '2024-01-18',
    estimatedHours: 20,
    completedHours: 18,
    tags: ['Database', 'Performance'],
  },
  {
    id: 'task-4',
    projectId: 'proj-4',
    title: 'Mobile Adaptation',
    description: 'Ensure good experience on mobile devices',
    status: 'done',
    priority: 'medium',
    assignee: 'Zhao Liu',
    dueDate: '2024-01-10',
    estimatedHours: 24,
    completedHours: 24,
    tags: ['Frontend', 'Mobile'],
  },
  {
    id: 'task-5',
    projectId: 'proj-1',
    title: 'Security Fix',
    description: 'Fix discovered security vulnerabilities',
    status: 'todo',
    priority: 'urgent',
    assignee: 'Qian Qi',
    dueDate: '2024-01-12',
    estimatedHours: 8,
    completedHours: 0,
    tags: ['Security', 'Fix'],
  },
];

const defects: Defect[] = [
  {
    id: 'DEF-001',
    projectId: 'proj-1',
    title: 'Login page submission issue',
    description: 'Page unresponsive after clicking login button, network error in console',
    status: 'open',
    severity: 'high',
    type: 'bug',
    assignee: 'Zhang San',
    reporter: 'Li Si',
    createdDate: '2024-01-10',
    dueDate: '2024-01-15',
    environment: 'Production',
    steps: ['Open login page', 'Enter username and password', 'Click login button', 'Observe response'],
  },
  {
    id: 'DEF-002',
    projectId: 'proj-1',
    title: 'Slow page loading',
    description: 'Homepage takes more than 5 seconds to load',
    status: 'in_progress',
    severity: 'medium',
    type: 'performance',
    assignee: 'Wang Wu',
    reporter: 'Zhao Liu',
    createdDate: '2024-01-08',
    dueDate: '2024-01-20',
    environment: 'Testing',
    steps: ['Visit homepage', 'Record load time', 'Analyze bottlenecks'],
  },
  {
    id: 'DEF-003',
    projectId: 'proj-4',
    title: 'Mobile layout issue',
    description: 'Navigation menu displays incorrectly on small screens',
    status: 'resolved',
    severity: 'medium',
    type: 'ui',
    assignee: 'Qian Qi',
    reporter: 'Sun Ba',
    createdDate: '2024-01-05',
    dueDate: '2024-01-12',
    environment: 'Mobile',
    steps: ['Use phone to visit', 'Check navigation', 'Test responsive layout'],
  },
  {
    id: 'DEF-004',
    projectId: 'proj-1',
    title: 'Data leakage risk',
    description: 'API interfaces lack proper authentication',
    status: 'open',
    severity: 'critical',
    type: 'security',
    assignee: 'Zhou Jiu',
    reporter: 'Wu Shi',
    createdDate: '2024-01-12',
    dueDate: '2024-01-14',
    environment: 'Production',
    steps: ['Test API', 'Check authentication', 'Assess risk'],
  },
  {
    id: 'DEF-005',
    projectId: 'proj-4',
    title: 'IE browser compatibility',
    description: 'Some features not working in IE11',
    status: 'closed',
    severity: 'low',
    type: 'compatibility',
    assignee: 'Zheng Shi Yi',
    reporter: 'Wang Shi Er',
    createdDate: '2024-01-01',
    dueDate: '2024-01-10',
    environment: 'IE11',
    steps: ['Open in IE11', 'Test features', 'Record issues'],
  },
];

export { users, customers, invoices, revenue, projects, requirements, tasks, defects };
